#!/bin/sh
#SBATCH --job-name="step46_teacher_pipeline"
#SBATCH --partition=gpu
#SBATCH --gres=gpu:3g.40gb:1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem=32G
#SBATCH --time=02-06:00:00
#SBATCH -o slurm.%N.%j.out
#SBATCH -e slurm.%N.%j.err

cd /parallel_scratch/sl02092/standard_project

export HF_HUB_OFFLINE=1

apptainer exec --nv oras://container-registry.surrey.ac.uk/shared-containers/pytorch:latest \
    /parallel_scratch/sl02092/standard_project/venv/bin/python3 step46_hybrid_teacher_pipeline_final.py
